### ISSUE TITLE
Unexpected non deterministic results

### ISSUE THREAD

**Issue by pbaille** [clojure/data.generators#12]
If I understand correctly the following form should always return the same value but it don't

``` clojure
(in-ns 'clojure.data.generators)
(binding [*rnd* (java.util.Random. 42)]
  (cons (int)
        (lazy-seq (core/list (int)))))
```

Here 3 different outputs:
```
'(977378563 1568399832)
'(977378563 1807067325)
'(977378563 119846206)
```

The first number remain the same accros evaluations, but the second varies. It seems to be due to `lazy-seq` wrapping.

**Comment by bendlas** [comment]
I don't think the clojure org accepts github issues, but FWIW this doesn't look like a bug in `data.generators` either:

`lazy-seq` creates a closure, which is only called on demand. This loses the `binding` in all cases where the sequence is not realized inside the binding. Try to either remove the lazyness, or repeat the `binding` inside of the `lazy-seq`.

**Comment by pbaille** [comment]
Ok it make sense, I understand the behavior now. Thank you. I close the issue
