### ISSUE TITLE
int and short doc strings

### ISSUE THREAD

**Issue by greghendershott** [clojure/data.generators#9]
The [definitions of `int` and `short`](https://github.com/clojure/data.generators/blob/master/src/main/clojure/clojure/data/generators.clj#L102-L110) both have the doc string and arg vector reversed.

And then it would be good to update their doc strings: Currently both mention `long`: `"Returns a long based on *rnd* in the int range."`.

**Comment by puredanger** [comment]
This repo doesn't use github issues but I have made the changes for the next release.

**Comment by greghendershott** [comment]
Ah, I'm sorry for putting this in the wrong issue bucket. Thank you for fielding it anyway.
